### PR TITLE
Use disk.unique name for LVM operations

### PR DESCRIPTION
**Pull request by jsuchome**
Use disk.unique name for LVM operations, it was already used for claiming anyway

(bnc#931048)

### CODE REVIEW

**Comment by aspiers** [comment]
I don't trust my jetlagged brain right now, but this sounds good to me.

**Comment by mjura** [comment]
+1

**Comment by tboerger** [comment]
LGTM

**Comment by jsuchome** [comment]
I'm just waiting for customer response...

**Comment by vuntz** [comment]
+1, but would like to be sure this was tested before merging :-)

**Comment by jsuchome** [comment]
@vuntz deployment of pacemaker + DB (with this patch included) went fine for me.

**Comment by aspiers** [comment]
FWIW this breaks SLE12 HA clusters due to a change in `lvm.conf`'s `filter` option's default value on SLE12.

**Pull request merged**
