### PR TITLE
Allow deploying pacemaker on SLE12

### PR DESCRIPTION
**Pull request by aspiers**
There are still some remaining issues, but this is a good start.

Supercedes #196.

### CODE REVIEW

**Comment by aspiers** [comment]
As expected, this fails because SLE12 `lvm.conf` excludes `/dev/disk/by-id/.*`.  @dirkmueller any suggestions on how to handle this?

**Comment by dirkmueller** [comment]
@aspiers can you add the revert of the change to disk/by-id ? it was not positively tested by the customer, and if it resolves the issue, it would at least help us getting forward.

**Comment by aspiers** [comment]
For ease of future reference, I think @dirkmueller is suggesting to revert #198 which was made as a result of https://bugzilla.suse.com/show_bug.cgi?id=931048.  I agree with your suggestion so I will revert it - #198 seems like a slightly dumb workaround hack, and as Jiri said in the bug, the proper solution is https://trello.com/c/VaemNu77/736-5-crowbar-add-ability-to-assign-intended-role-to-disks-of-a-node-to-help-with-claiming which is already in progress.  @jsuchome can you see any problems with reverting #198?

**Comment by dirkmueller** [comment]
LGTM and safe to me. can we merge it?

**Comment by rsalevsky** [comment]
LGTM

**Comment by aspiers** [comment]
Merging on Dirk's advice, and also based on the fact that the gate failure can't be related because that doesn't use the pacemaker barclamp at all (yet).

**Pull request merged**
