### PR TITLE
Backport #185 and #186 to stoney

### PR DESCRIPTION
**Pull request by aspiers**
This backports #185 and #186 to `release/stoney/master`.

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by tboerger** [comment]
:+1:

**Comment by aspiers** [comment]
-1, turns out that the fix in #186 isn't quite right.

**Comment by aspiers** [comment]
Still WIP, but marked by a label now.  It seems I / we somehow forgot about this :-/

**Comment by rsalevsky** [comment]
Cloud 5 (Tex) is EOL since 15th May 2017 if this patch is still required please open a new pull request.

**Pull request closed without merging**
