### PR TITLE
Setup monitoring for STONITH resources

### PR DESCRIPTION
**Pull request by jsuchome**
Couple of hours is good kind of interval value for
STONITH monitoring.

This is tex backport of https://github.com/crowbar/crowbar-ha/pull/93

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
+1

**Comment by jsuchome** [comment]
I'll test that as well, in Cloud5 setup

**Comment by jsuchome** [comment]
.. yes, works correctly with Cloud5 as well.

**Pull request merged**
