### PR TITLE
Don't escape html for quorum doc link

### PR DESCRIPTION
**Pull request by toabctl**
Otherwise, the whole `<a href=...>` is shown.

### CODE REVIEW

**Comment by toabctl** [comment]
just to remember: when this got merged, the patch in D:C:5:S with the SUSE link must be updated.

**Comment by aspiers** [comment]
Why does this prevent escaping?  Is there some magic which detects the `_html` suffix and changes behaviour accordingly?

**Comment by toabctl** [comment]
> Why does this prevent escaping? Is there some magic which detects the _html suffix and changes behaviour accordingly?

@aspiers Yes, it's magic. See http://guides.rubyonrails.org/i18n.html "4.5 Using Safe HTML Translations". And I tested it and it works.

**Comment by aspiers** [comment]
Very nice, in that case :+1: :)

**Comment by dirkmueller** [comment]
+1

**Comment by tboerger** [comment]
For multiple other places we just appended a .html_safe to get the html output.

**Pull request merged**
