### PR TITLE
fix for bsc#922751

### PR DESCRIPTION
**Pull request by aspiers**
Fix for https://bugzilla.suse.com/show_bug.cgi?id=922751

### CODE REVIEW

**Comment by vuntz** [comment]
Hrm, you also need to change the `configure_command` for primitives (since we override it there)

**Comment by tboerger** [comment]
Intresting, looks good so far.

**Comment by aspiers** [comment]
@vuntz Rebased and ditched the override which should be unnecessary (in theory).

**Comment by aspiers** [comment]
I have now tested this and it should be ready to merge.

**Comment by vuntz** [comment]
@aspiers just to be 100% sure: have you tested with the case where the pacemaker resource doesn't exist yet? Just to make sure that `crm configure load update` also works for non-existing resources.

**Comment by aspiers** [comment]
@vuntz Yes I did.  That's why I was bitching about issues with `mkcloud`'s PTF repo support (e.g. https://github.com/SUSE-Cloud/automation/issues/291) on IRC yesterday :)

**Comment by vuntz** [comment]
+1

**Comment by aspiers** [comment]
I guess we can wait for customer feedback before merging?

**Comment by vuntz** [comment]
We can, but there's no need to.

**Comment by vuntz** [comment]
Note that we'll need a backport to stoney.

**Comment by aspiers** [comment]
As per https://bugzilla.suse.com/show_bug.cgi?id=922751#c12 this fix wasn't quite right :-(

**Pull request merged**
